#!/usr/bin/env python

import sys

def main (argv=None):
    if not argv: argv = sys.argv
    if len(argv) > 1:
        outfile = file(argv[1], "wt")
        print >> sys.stderr, "testecho: using", argv[1], "as output"
    else:
        print >> sys.stderr, "testecho: Warning, using stdout as output"
        print >> sys.stderr, argv
        outfile = sys.stdout
    try:
        while 1:
            outfile.write(raw_input())
            outfile.write('\n')
            outfile.flush()
    except:
        pass
    outfile.close()
    return 0

if __name__ == '__main__':
    sys.exit(main())

