#!/usr/bin/env python

import sys

def main (argv=None):
    if not argv: argv = sys.argv
    assert(len(argv) > 1)
    print 'TESTECHO Using file ', argv[1]
    try:
        outfile = file(argv[1], "wt")
        while 1:
            outfile.write(raw_input())
            outfile.flush()
    except:
        pass
    outfile.close()
    return 0

if __name__ == '__main__':
    sys.exit(main())

