#!/usr/bin/env python

import sys

def main (argv=None):
    if not argv: argv = sys.argv
    print >> sys.stderr, "args: ", str(argv)
    try:
        while 1:
            print >> sys.stderr, raw_input()
    except:
        pass
    return 0

if __name__ == '__main__':
    sys.exit(main())

